all: create

create: 
	gcc main.c -o prog.out
	ln prog.out cdir.out
	ln prog.out pdir.out
	ln prog.out rdir.out
	ln prog.out cfile.out
	ln prog.out rfile.out
	ln prog.out csym.out
	ln prog.out psym.out
	ln prog.out psymtarget.out
	ln prog.out rsym.out
	ln prog.out chard.out
	ln prog.out pperm.out
	ln prog.out chperm.out
	rm prog.out
clean:
	rm -f *.out
